import Head from 'next/head';
import { ColorModeScript } from '@chakra-ui/react';
import Header from '../sections/header';
import Hero from '../sections/hero';
import Hero2 from '../sections/hero2';
import About from '../sections/about';
import How from '../sections/how';
import Stats from '../sections/stats';
import { theme } from '../styles/theme';
import Feedback from '../sections/feedback';
import Competition from '../sections/competition';
import SetUs from '../sections/set_us';

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <ColorModeScript initialColorMode={theme.initialColorMode} />
                <Header />
                <Hero />
                <About />
                <How />
                <Stats />
                <Feedback />
                <Competition />
                <SetUs />
            </main>
        </>
    );
}
